# Generated by Django 3.2.2 on 2021-05-07 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Job_Type', models.CharField(choices=[('Full Time', 'Part Time'), ('Full Time', 'Part Time')], max_length=15)),
                ('description', models.TextField(max_length=500)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('salary', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('vacancy', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to=job.models.upload_image)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cv', models.FileField(upload_to='uploads/')),
                ('cover_letter', models.TextField(max_length=200)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=50)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job')),
            ],
        ),
    ]
