# Generated by Django 3.2.2 on 2021-05-19 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_auto_20210519_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='website',
        ),
        migrations.AddField(
            model_name='job',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
